import { FightRenderer } from "./render/renderer";
import type { EngineSnapshot, FighterSnapshot, PublicPlayer } from "./types";
const fighter = (id: string, x: number, facing: number): FighterSnapshot => ({ player_id: id, x, y: 0, facing, velocity_x: 0, velocity_y: 0, stance: id === "fixture-one" ? "orthodox" : "southpaw", defense: id === "fixture-one" ? "guard_high" : "slip_left", stamina: 760, maximum_stamina: 1000, conditioning: 820, guard: 670, poise: 520, trauma: { head: id === "fixture-two" ? 230 : 80, body: 110, left_eye: 90, right_eye: 25, left_cut: 45, right_cut: 0, swelling: 65, bleeding: 35 }, knockdowns: id === "fixture-two" ? 1 : 0, warnings: 0, deductions: 0, stunned_ticks: 0, is_downed: false, action: id === "fixture-one" ? "hook" : null, action_hand: id === "fixture-one" ? "left" : null, action_target: id === "fixture-one" ? "head" : null, action_power: id === "fixture-one" ? "power" : null, queued_actions: 0, clinch_startup_ticks: 0, clinch_ticks: 0, is_foul_recovery_target: false, get_up_prompt: null, get_up_meter: 0, get_up_required: 0, get_up_count: 0, get_up_window_start_tick: 0, get_up_window_end_tick: 0 });
export function runDevelopmentFixture(root: HTMLElement): () => void {
  root.innerHTML = `<section class="activity"><canvas class="fight"></canvas><header class="topbar"><strong>HANDS · DEV FIXTURE</strong><span>Production never enters this harness</span></header></section>`;
  const renderer = new FightRenderer(root.querySelector("canvas")!, { tick_rate: 30, ring_half_width: 6000, ring_half_height: 4000 }, () => ({ volume: 0, haptics: false, reducedMotion: false, blood: "full" }));
  const players: Record<string, PublicPlayer> = { "fixture-one": { id: "fixture-one", name: "Azure Vector", avatar: null, rating: 1512, connected: true }, "fixture-two": { id: "fixture-two", name: "Crimson Geometry", avatar: null, rating: 1494, connected: true } }; renderer.setPlayers(players, "fixture-one");
  const snapshot: EngineSnapshot = { tick: 900, phase: "fight", round_number: 3, phase_ticks_remaining: 2030, fighters: [fighter("fixture-one", -1250, 1), fighter("fixture-two", 1180, -1)], events: [{ event_id: 18, tick: 900, kind: "counter_hit", actor_id: "fixture-one", target_id: "fixture-two", amount: 160, detail: "left hook head", blood: 44, direction: 1 }], result: null, checksum: "a".repeat(64) };
  renderer.push(snapshot); return () => { renderer.destroy(); root.replaceChildren(); };
}
