import { KeyboardInput } from "./keyboard";
const key = (type: "keydown" | "keyup", code: string, repeat = false): KeyboardEvent => new KeyboardEvent(type, { code, repeat, cancelable: true });
describe("semantic keyboard parity", () => {
  it("emits all punch fields with latched modifiers and held movement/guard", () => { const input = new KeyboardInput(); window.dispatchEvent(key("keydown", "ShiftLeft")); window.dispatchEvent(key("keydown", "AltLeft")); window.dispatchEvent(key("keydown", "KeyA")); window.dispatchEvent(key("keydown", "KeyQ")); window.dispatchEvent(key("keydown", "KeyF")); expect(input.frame()).toEqual({ moveX: -1000, moveY: 0, defense: "guard_high", actions: [{ kind: "punch", hand: "left", class: "jab", target: "body", power: "power" }] }); input.destroy(); });
  it("covers evasions, clinch, stance, fouls and get-up without repeat", () => { const input = new KeyboardInput(window, 20); for (const code of ["KeyZ", "KeyX", "KeyC", "KeyV", "KeyB", "KeyN", "Digit1", "Digit2", "ArrowLeft", "ArrowRight"]) window.dispatchEvent(key("keydown", code)); window.dispatchEvent(key("keydown", "KeyZ", true)); const actions = [...input.frame(20).actions]; expect(actions.map((action) => action.kind)).toEqual(["slip_left", "slip_right", "weave", "pull", "clinch", "switch_stance", "foul", "foul", "get_up_left", "get_up_right"]); window.dispatchEvent(new Event("blur")); expect(input.frame().actions).toEqual([]); input.destroy(); });
  it("maps W up and S down, normalizes diagonals and becomes neutral on blur", () => { const input = new KeyboardInput(); window.dispatchEvent(key("keydown", "KeyA")); window.dispatchEvent(key("keydown", "KeyW")); expect(input.frame()).toMatchObject({ moveX: -707, moveY: 707 }); window.dispatchEvent(key("keyup", "KeyW")); window.dispatchEvent(key("keydown", "KeyS")); expect(input.frame()).toMatchObject({ moveX: -707, moveY: -707 }); window.dispatchEvent(new Event("blur")); expect(input.frame()).toMatchObject({ moveX: 0, moveY: 0, defense: "none", actions: [] }); input.destroy(); });
  it("coalesces rapid repeats of the same discrete key", () => { const input = new KeyboardInput(window, 3); for (let index = 0; index < 100; index += 1) { window.dispatchEvent(key("keydown", "KeyF")); window.dispatchEvent(key("keyup", "KeyF")); } const actions = input.frame(20).actions; expect(actions).toEqual([{ kind: "punch", hand: "left", class: "jab", target: "head", power: "normal" }]); input.destroy(); });
  it("retains only the newest changed intent", () => { const input = new KeyboardInput(window, 1); for (const code of ["KeyF", "KeyJ", "KeyG"]) { window.dispatchEvent(key("keydown", code)); window.dispatchEvent(key("keyup", code)); } expect(input.frame(20).actions).toEqual([{ kind: "punch", hand: "left", class: "hook", target: "head", power: "normal" }]); input.destroy(); });
  it("cancels stale intent when guard starts but allows a new punch from guard", () => { const input = new KeyboardInput(); window.dispatchEvent(key("keydown", "KeyF")); window.dispatchEvent(key("keyup", "KeyF")); window.dispatchEvent(key("keydown", "KeyQ")); expect(input.frame()).toEqual({ moveX: 0, moveY: 0, defense: "guard_high", actions: [] }); window.dispatchEvent(key("keydown", "KeyF")); expect(input.frame().actions).toEqual([{ kind: "punch", hand: "left", class: "jab", target: "head", power: "normal" }]); input.destroy(); });
});
