import type { EngineSnapshot, FinalMessage, PublicPlayer } from "../types";
export const HUD_MAX_GUARD = 700;
export const HUD_MAX_POISE = 600;
export const scoreTotal = (scores: readonly number[]): number => scores.reduce((sum, score) => sum + score, 0);
const fit = (ctx: CanvasRenderingContext2D, text: string, width: number): string => { if (ctx.measureText(text).width <= width) return text; let value = text; while (value.length > 1 && ctx.measureText(`${value}…`).width > width) value = value.slice(0, -1); return `${value}…`; };
const bar = (ctx: CanvasRenderingContext2D, x: number, y: number, width: number, value: number, maximum: number, color: string, label: string): void => { ctx.fillStyle = "rgba(4,7,12,.72)"; ctx.fillRect(x, y, width, 8); ctx.fillStyle = color; ctx.fillRect(x, y, width * Math.max(0, Math.min(1, value / Math.max(1, maximum))), 8); ctx.fillStyle = "#eaf2ff"; ctx.font = "600 10px system-ui,sans-serif"; ctx.fillText(label, x, y - 3); };
export function drawHud(ctx: CanvasRenderingContext2D, width: number, height: number, snapshot: EngineSnapshot, players: Readonly<Record<string, PublicPlayer>>, viewerId: string | null, final: FinalMessage | null, reconnectMs: number, tickRate = 30): void {
  ctx.save(); ctx.textBaseline = "alphabetic"; const left = snapshot.fighters[0], right = snapshot.fighters[1]; const sideWidth = Math.min(260, width * 0.36);
  for (const [index, fighter] of snapshot.fighters.entries()) { const x = index === 0 ? 20 : width - 20 - sideWidth; const player = players[fighter.player_id]; ctx.fillStyle = "rgba(4,8,14,.78)"; ctx.fillRect(x - 8, 12, sideWidth + 16, 88); ctx.fillStyle = "#f5f7ff"; ctx.font = "700 15px system-ui,sans-serif"; ctx.fillText(fit(ctx, player?.name ?? "Fighter", sideWidth - 80), x, 33); ctx.fillStyle = "#aebbd0"; ctx.font = "12px system-ui,sans-serif"; ctx.fillText(`ELO ${player?.rating ?? "—"} · KD ${fighter.knockdowns} · W ${fighter.warnings} · −${fighter.deductions}`, x, 49); bar(ctx, x, 62, sideWidth, fighter.stamina, fighter.maximum_stamina, "#39d891", `STAMINA ${Math.round(fighter.stamina)}/${Math.round(fighter.maximum_stamina)}`); bar(ctx, x, 79, sideWidth * 0.48, fighter.guard, HUD_MAX_GUARD, "#61a7ff", "GUARD"); bar(ctx, x + sideWidth * 0.52, 79, sideWidth * 0.48, fighter.poise, HUD_MAX_POISE, "#d6a35d", `POISE · COND ${fighter.conditioning}`); }
  ctx.textAlign = "center"; ctx.fillStyle = "rgba(4,8,14,.82)"; ctx.fillRect(width / 2 - 75, 12, 150, 58); ctx.fillStyle = "#f6d57a"; ctx.font = "800 15px system-ui,sans-serif"; ctx.fillText(`ROUND ${snapshot.round_number}`, width / 2, 34); ctx.fillStyle = "white"; ctx.font = "700 18px ui-monospace,monospace"; ctx.fillText(`${Math.floor(snapshot.phase_ticks_remaining / (tickRate * 60))}:${String(Math.floor(snapshot.phase_ticks_remaining / tickRate) % 60).padStart(2, "0")}`, width / 2, 57); ctx.fillStyle = "#aebbd0"; ctx.font = "11px system-ui,sans-serif"; ctx.fillText(snapshot.phase.replace("_", " ").toUpperCase(), width / 2, 69);
  if (snapshot.phase === "knockdown") { const viewer = snapshot.fighters.find((fighter) => fighter.player_id === viewerId); ctx.fillStyle = "rgba(4,7,12,.86)"; ctx.fillRect(width / 2 - 145, height - 105, 290, 72); ctx.fillStyle = "#ffd77a"; ctx.font = "800 23px system-ui,sans-serif"; ctx.fillText(`COUNT ${Math.max(...snapshot.fighters.map((f) => f.get_up_count))}`, width / 2, height - 74); if (viewer?.get_up_prompt !== null && viewer?.get_up_prompt !== undefined) { ctx.font = "600 14px system-ui,sans-serif"; ctx.fillText(`YOUR RHYTHM: ${viewer.get_up_prompt === "get_up_left" ? "←" : "→"}  ${viewer.get_up_meter}/${viewer.get_up_required}`, width / 2, height - 49); } }
  if (snapshot.phase === "foul_recovery") { const victim = snapshot.fighters.find((fighter) => fighter.is_foul_recovery_target); ctx.fillStyle = "rgba(4,7,12,.84)"; ctx.fillRect(width / 2 - 145, height / 2 - 34, 290, 68); ctx.fillStyle = "#ffd77a"; ctx.font = "800 18px system-ui,sans-serif"; ctx.fillText("FOUL RECOVERY", width / 2, height / 2 - 4); ctx.font = "12px system-ui,sans-serif"; ctx.fillText(`${players[victim?.player_id ?? ""]?.name ?? "Fighter"} is recovering`, width / 2, height / 2 + 19); }
  if (snapshot.phase === "rest") { ctx.fillStyle = "rgba(4,7,12,.84)"; ctx.fillRect(width / 2 - 120, height / 2 - 35, 240, 70); ctx.fillStyle = "#f6d57a"; ctx.font = "800 22px system-ui,sans-serif"; ctx.fillText("CORNERS · RECOVER", width / 2, height / 2); ctx.font = "12px system-ui,sans-serif"; ctx.fillText("Conditioning governs recovery", width / 2, height / 2 + 22); }
  if (reconnectMs > 0) { ctx.fillStyle = "rgba(4,7,12,.9)"; ctx.fillRect(width / 2 - 160, height / 2 - 30, 320, 60); ctx.fillStyle = "#ffd77a"; ctx.font = "700 17px system-ui,sans-serif"; ctx.fillText(`OPPONENT RECONNECTING · ${Math.ceil(reconnectMs / 1000)}s`, width / 2, height / 2 + 6); }
  if (final !== null) drawFinal(ctx, width, height, final, players);
  ctx.restore();
}
function drawFinal(ctx: CanvasRenderingContext2D, width: number, height: number, final: FinalMessage, players: Readonly<Record<string, PublicPlayer>>): void {
  ctx.fillStyle = "rgba(3,6,11,.94)"; ctx.fillRect(width * 0.12, height * 0.14, width * 0.76, height * 0.72); ctx.fillStyle = "#f6d57a"; ctx.font = "800 25px system-ui,sans-serif"; ctx.fillText(final.method.replaceAll("_", " ").toUpperCase(), width / 2, height * 0.21);
  const winner = final.winner_id === null ? "DRAW" : `${players[final.winner_id]?.name ?? "Winner"} WINS`; ctx.fillStyle = "white"; ctx.font = "700 18px system-ui,sans-serif"; ctx.fillText(fit(ctx, winner, width * 0.6), width / 2, height * 0.27);
  ctx.font = "12px ui-monospace,monospace"; final.scorecards.forEach((card, index) => { const y = height * 0.37 + index * 36; ctx.fillStyle = "#aebbd0"; ctx.fillText(`${fit(ctx, card.judge, 100)}  ${scoreTotal(card.player_one)} — ${scoreTotal(card.player_two)}  [${card.player_one.join("·")}] [${card.player_two.join("·")}]`, width / 2, y); });
  const ratings = Object.entries(final.ratings); ctx.font = "600 13px system-ui,sans-serif"; ratings.forEach(([id, rating], index) => { ctx.fillStyle = rating.after >= rating.before ? "#55df9b" : "#ff7b74"; ctx.fillText(`${fit(ctx, players[id]?.name ?? "Fighter", 100)}  ${rating.before} → ${rating.after} (${rating.after - rating.before >= 0 ? "+" : ""}${rating.after - rating.before})`, width / 2, height * 0.61 + index * 27); });
}
